services:
  web:
    image: kode_fastapi
    container_name: kode_fastapi
    volumes:
      - .:/app
    
    environment:  
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/kode_notes
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    networks:
      - kode

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: kode_notes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kode

volumes:
  postgres_data:

networks:
  kode:
    driver: bridge
